"""empty message

Revision ID: 24a79e7394e8
Revises: 
Create Date: 2019-02-17 18:54:10.015512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a79e7394e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imovel',
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('tipoImovel', sa.String(), nullable=True),
    sa.Column('areaImovel', sa.String(), nullable=True),
    sa.Column('enderecoUser', sa.String(), nullable=True),
    sa.Column('latUser', sa.String(), nullable=True),
    sa.Column('longUser', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('matricula')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imovel')
    # ### end Alembic commands ###
